<a href="https://colab.research.google.com/github/Samagratiwari/pedri_performance_analysis/blob/main/pedri_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

df_2020 = pd.read_excel("/content/pedri2020.xlsx")
df_2024 = pd.read_excel("/content/pedri2024.xlsx")

df_2020.head(), df_2024.head()

(           Performance Unnamed: 1 Unnamed: 2   Unnamed: 3 Unnamed: 4  \
 0                 Date        Day       Comp        Round      Venue
 1  2020-09-27 00:00:00        Sun    La Liga  Matchweek 3       Home
 2  2020-10-01 00:00:00        Thu    La Liga  Matchweek 4       Away
 3  2020-10-04 00:00:00        Sun    La Liga  Matchweek 5       Home
 4  2020-10-17 00:00:00        Sat    La Liga  Matchweek 6       Away

   Unnamed: 5 Unnamed: 6  Unnamed: 7 Unnamed: 8 Unnamed: 9  ... Unnamed: 19  \
 0     Result      Squad    Opponent      Start        Pos  ...         Fls
 1      W 4–0  Barcelona  Villarreal          N        NaN  ...           0
 2      W 3–0  Barcelona  Celta Vigo          N        NaN  ...           0
 3      D 1–1  Barcelona     Sevilla          N        NaN  ...           0
 4      L 0–1  Barcelona      Getafe          Y         AM  ...           0

   Unnamed: 20 Unnamed: 21 Unnamed: 22 Unnamed: 23 Unnamed: 24 Unnamed: 25  \
 0         Fld         Off         Crs        TklW         Int          OG
 1           1           0           0           0           0           0
 2           1           0           0           0           1           0
 3           0           0           0           2           1           0
 4           1           0           0           0           1           0

   Unnamed: 26 Unnamed: 27   Unnamed: 28
 0       PKwon       PKcon           NaN
 1         NaN         NaN           NaN
 2         NaN         NaN  Match Report
 3         NaN         NaN  Match Report
 4         NaN         NaN  Match Report

 [5 rows x 29 columns],
             Unnamed: 0 Unnamed: 1 Unnamed: 2   Unnamed: 3 Unnamed: 4  \
 0                 Date        Day       Comp        Round      Venue
 1                  NaN        NaN        NaN          NaN        NaN
 2  2024-08-17 00:00:00        Sat    La Liga  Matchweek 1       Away
 3  2024-08-24 00:00:00        Sat    La Liga  Matchweek 2       Home
 4  2024-08-27 00:00:00        Tue    La Liga  Matchweek 3       Away

   Unnamed: 5 Unnamed: 6      Unnamed: 7 Unnamed: 8 Unnamed: 9  ...  \
 0     Result      Squad        Opponent      Start        Pos  ...
 1        NaN        NaN             NaN        NaN        NaN  ...
 2      W 2–1  Barcelona        Valencia          N        NaN  ...
 3      W 2–1  Barcelona   Athletic Club          Y         DM  ...
 4      W 2–1  Barcelona  Rayo Vallecano          Y         DM  ...

   Unnamed: 18 Unnamed: 19 Unnamed: 20 Unnamed: 21 Unnamed: 22 Unnamed: 23  \
 0        CrdR         Fls         Fld         Off         Crs        TklW
 1         NaN         NaN         NaN         NaN         NaN         NaN
 2           0           0           0           0           0           1
 3           0           0           0           0           1           1
 4           0           1           4           0           1           0

   Unnamed: 24 Unnamed: 25 Unnamed: 26 Unnamed: 27
 0         Int          OG       PKwon       PKcon
 1         NaN         NaN         NaN         NaN
 2           0           0         NaN         NaN
 3           1           0         NaN         NaN
 4           1           0         NaN         NaN

 [5 rows x 28 columns])

In [5]:
df_2020.columns = df_2020.iloc[0]
df_2020 = df_2020[1:]

df_2024.columns = df_2024.iloc[0]
df_2024 = df_2024[1:]

In [6]:
df_2020 = df_2020.reset_index(drop=True)
df_2024 = df_2024.reset_index(drop=True)

In [7]:
df_2020.head()

1,2020-09-27 00:00:00,Sun,La Liga,Matchweek 3,Home,W 4–0,Barcelona,Villarreal,N,NaN,...,0,1,0,0,0,0,0,NaN,NaN,NaN
0,2020-10-01 00:00:00,Thu,La Liga,Matchweek 4,Away,W 3–0,Barcelona,Celta Vigo,N,NaN,...,0,1,0,0,0,1,0,NaN,NaN,Match Report
1,2020-10-04 00:00:00,Sun,La Liga,Matchweek 5,Home,D 1–1,Barcelona,Sevilla,N,NaN,...,0,0,0,0,2,1,0,NaN,NaN,Match Report
2,2020-10-17 00:00:00,Sat,La Liga,Matchweek 6,Away,L 0–1,Barcelona,Getafe,Y,AM,...,0,1,0,0,0,1,0,NaN,NaN,Match Report
3,2020-10-20 00:00:00,Tue,Champions Lg,Group stage,Home,W 5–1,es Barcelona,hu Ferencváros,N,NaN,...,0,1,0,0,1,0,0,NaN,NaN,Match Report
4,2020-10-24 00:00:00,Sat,La Liga,Matchweek 7,Home,L 1–3,Barcelona,Real Madrid,Y,RM,...,0,1,0,0,0,1,0,NaN,NaN,Match Report

In [8]:
df_2020 = pd.read_excel("/content/pedri2020.xlsx", header=1)
df_2024 = pd.read_excel("/content/pedri2024.xlsx", header=1)

In [9]:
df_2020.head()

,Date,Day,Comp,Round,Venue,Result,Squad,Opponent,Start,Pos,...,Fls,Fld,Off,Crs,TklW,Int,OG,PKwon,PKcon,Unnamed: 28
0,2020-09-27 00:00:00,Sun,La Liga,Matchweek 3,Home,W 4–0,Barcelona,Villarreal,N,NaN,...,0,1,0,0,0,0,0,NaN,NaN,NaN
1,2020-10-01 00:00:00,Thu,La Liga,Matchweek 4,Away,W 3–0,Barcelona,Celta Vigo,N,NaN,...,0,1,0,0,0,1,0,NaN,NaN,Match Report
2,2020-10-04 00:00:00,Sun,La Liga,Matchweek 5,Home,D 1–1,Barcelona,Sevilla,N,NaN,...,0,0,0,0,2,1,0,NaN,NaN,Match Report
3,2020-10-17 00:00:00,Sat,La Liga,Matchweek 6,Away,L 0–1,Barcelona,Getafe,Y,AM,...,0,1,0,0,0,1,0,NaN,NaN,Match Report
4,2020-10-20 00:00:00,Tue,Champions Lg,Group stage,Home,W 5–1,es Barcelona,hu Ferencváros,N,NaN,...,0,1,0,0,1,0,0,NaN,NaN,Match Report

In [10]:
df_2020['Season'] = "2020-21"
df_2024['Season'] = "2024-25"

df = pd.concat([df_2020, df_2024], ignore_index=True)

In [11]:
cols = ['Min','Gls','Ast','Sh','SoT','TklW','Int']

for col in cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [12]:
df['min_per_match'] = df['Min']

season_avg = df.groupby('Season')['min_per_match'].mean()
avg_minutes = season_avg.mean()

df['Fitness'] = df['Season'].map(
    lambda x: 'Fit' if season_avg[x] > avg_minutes else 'Unfit'
)

print(season_avg)

Season
2020-21    134.786885
2024-25    145.100000
Name: min_per_match, dtype: float64

In [13]:
df = df[df['Min'] <= 120]

In [14]:
df = df[df['Min'].notna()]

In [15]:
df['Min'] = pd.to_numeric(df['Min'], errors='coerce')

In [16]:
season_avg = df.groupby('Season')['Min'].mean()
print(season_avg)

Season
2020-21    68.516667
2024-25    73.550725
Name: Min, dtype: float64

In [17]:
new_rows = pd.DataFrame([
    {
        "Date": "2021-07-02",
        "Day": "Fri",
        "Comp": "UEFA Euro",
        "Round": "Quarter-finals",
        "Venue": "Away",
        "Result": "D 1 (3)–1 (1)",
        "Squad": "es Spain",
        "Opponent": "ch Switzerland",
        "Start": "Y",
        "Pos": "CM",
        "Min": 118,
        "Gls": 0,
        "Ast": 0,
        "PK": 0,
        "PKatt": 0,
        "Sh": 0,
        "SoT": 0,
        "CrdY": 0,
        "CrdR": 0,
        "Fls": 1,
        "Fld": 1,
        "Off": 0,
        "Crs": 0,
        "TklW": 1,
        "Int": 2,
        "OG": 0,
        "PKwon": None,
        "PKcon": None
    },
    {
        "Date": "2021-07-06",
        "Day": "Tue",
        "Comp": "UEFA Euro",
        "Round": "Semi-finals",
        "Venue": "Away",
        "Result": "D 1 (2)–1 (4)",
        "Squad": "es Spain",
        "Opponent": "it Italy",
        "Start": "Y",
        "Pos": "CM",
        "Min": 120,
        "Gls": 0,
        "Ast": 0,
        "PK": 0,
        "PKatt": 0,
        "Sh": 0,
        "SoT": 0,
        "CrdY": 0,
        "CrdR": 0,
        "Fls": 0,
        "Fld": 2,
        "Off": 0,
        "Crs": 0,
        "TklW": 0,
        "Int": 1,
        "OG": 0,
        "PKwon": None,
        "PKcon": None
    }
])

df_2020 = pd.concat([df_2020, new_rows], ignore_index=True)

In [18]:
df_2020['Min'] = pd.to_numeric(df_2020['Min'], errors='coerce')
df_2020['Min'].mean()

np.float64(134.28571428571428)

In [19]:
df_2020 = df_2020[df_2020['Comp'].notna()]

In [20]:
df_2020 = df_2020[df_2020['Comp'] != 'Comp']

In [21]:
df_2020['Min'] = pd.to_numeric(df_2020['Min'], errors='coerce')

In [22]:
df_2020 = df_2020[df_2020['Min'] <= 120]

In [23]:
df_2020['Min'].mean()

np.float64(70.14516129032258)

In [24]:
import pandas as pd

files = {
    "2019-20": "pedri2019.xlsx",
    "2020-21": "pedri2020.xlsx",
    "2021-22": "pedri2021.xlsx",
    "2022-23": "pedri2022.xlsx",
    "2023-24": "pedri2023.xlsx",
    "2024-25": "pedri2025(ongoing).xlsx"
}

dfs = []

for season, file in files.items():
    # Read the excel file without a header
    df_raw = pd.read_excel(f"/content/{file}", header=None)

    header_row_index = None
    # Search for 'Comp' column in the first few rows to identify the actual header
    for i in range(min(5, len(df_raw))):
        # Check if 'Comp' exists in the current row's values (case-sensitive)
        if 'Comp' in df_raw.iloc[i].values:
            header_row_index = i
            break

    if header_row_index is None:
        print(f"Warning: Could not find 'Comp' in header row for {file}. Skipping this file.")
        continue

    # Set the identified row as the header
    df_temp = df_raw.iloc[header_row_index:].copy()
    df_temp.columns = df_temp.iloc[0]
    df_temp = df_temp[1:].reset_index(drop=True)

    # Ensure column names are strings (sometimes they are mixed types after read_excel)
    df_temp.columns = df_temp.columns.astype(str)

    # Check again if 'Comp' exists after header processing
    if 'Comp' not in df_temp.columns:
        print(f"Error: 'Comp' column missing after header processing for {file}. Skipping.")
        continue

    # remove repeated header rows
    df_temp = df_temp[df_temp['Comp'] != 'Comp']

    # convert minutes column properly
    df_temp['Min'] = pd.to_numeric(df_temp['Min'], errors='coerce')

    # remove invalid rows (like totals, blanks, etc.)
    df_temp = df_temp[df_temp['Min'] <= 120]

    # add season column
    df_temp['Season'] = season

    dfs.append(df_temp)

# combine all seasons into one dataframe
df = pd.concat(dfs, ignore_index=True)

# calculate average minutes per season
season_avg = df.groupby('Season')['Min'].mean()

print(season_avg)

KeyError: 'Comp'

In [25]:
import pandas as pd

files = {
    "2019-20": "pedri2019.xlsx",
    "2020-21": "pedri2020.xlsx",
    "2021-22": "pedri2021.xlsx",
    "2022-23": "pedri2022.xlsx",
    "2023-24": "pedri2023.xlsx",
    "2024-25": "pedri2025(ongoing).xlsx"
}

dfs = []

for season, file in files.items():
    df_temp = pd.read_excel(f"/content/{file}", header=1)

    # 🔹 Fix column names (strip spaces)
    df_temp.columns = df_temp.columns.str.strip()

    # 🔹 Remove repeated headers ONLY if Comp exists
    if 'Comp' in df_temp.columns:
        df_temp = df_temp[df_temp['Comp'] != 'Comp']

    # 🔹 Convert minutes safely
    if 'Min' in df_temp.columns:
        df_temp['Min'] = pd.to_numeric(df_temp['Min'], errors='coerce')
        df_temp = df_temp[df_temp['Min'] <= 120]

    # 🔹 Add season
    df_temp['Season'] = season

    dfs.append(df_temp)

# combine all
df = pd.concat(dfs, ignore_index=True)

# calculate averages
season_avg = df.groupby('Season')['Min'].mean()

print(season_avg)

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

In [26]:
import pandas as pd

files = {
    "2019-20": "pedri2019.xlsx",
    "2020-21": "pedri2020.xlsx",
    "2021-22": "pedri2021.xlsx",
    "2022-23": "pedri2022.xlsx",
    "2023-24": "pedri2023.xlsx",
    "2024-25": "pedri2025(ongoing).xlsx"
}

dfs = []

for season, file in files.items():
    df_temp = pd.read_excel(f"/content/{file}", header=1)
    df_temp.columns = [str(col).strip() for col in df_temp.columns]
    df_temp = df_temp.loc[:, ~df_temp.columns.duplicated()]

    if 'Comp' in df_temp.columns:
        df_temp = df_temp[df_temp['Comp'] != 'Comp']

    if 'Min' in df_temp.columns:
        df_temp['Min'] = pd.to_numeric(df_temp['Min'], errors='coerce')
        df_temp = df_temp[df_temp['Min'] <= 120]

    df_temp['Season'] = season
    dfs.append(df_temp)

df = pd.concat(dfs, ignore_index=True)

season_avg = df.groupby('Season')['Min'].mean()
print(season_avg)

Season
2019-20    78.416667
2020-21    68.516667
2021-22    75.000000
2022-23    77.000000
2023-24          NaN
2024-25    70.577778
Name: Min, dtype: float64

In [27]:
df_test = pd.read_excel("/content/pedri2023.xlsx", header=1)
print(df_test.columns)
df_test.head()

Index([2023-08-13 00:00:00,               'Sun',           'La Liga',
             'Matchweek 1',              'Away',             'D 0–0',
               'Barcelona',            'Getafe',                 'Y',
                      'AM',                  78,                   0,
                     '0.1',               '0.2',               '0.3',
                         1,               '0.4',               '0.5',
                     '0.6',               '0.7',               '1.1',
                     '0.8',               '0.9',               '1.2',
                    '0.10',              '0.11',       'Unnamed: 26',
             'Unnamed: 27'],
      dtype='object')

,2023-08-13 00:00:00,Sun,La Liga,Matchweek 1,Away,D 0–0,Barcelona,Getafe,Y,AM,...,0.6,0.7,1.1,0.8,0.9,1.2,0.10,0.11,Unnamed: 26,Unnamed: 27
0,2023-08-20 00:00:00,Sun,La Liga,Matchweek 2,Home,W 2–0,Barcelona,Cádiz,Y,AM,...,0,1,2,0,2,2,0,0,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-11-04 00:00:00,Sat,La Liga,Matchweek 12,Away,W 1–0,Barcelona,Real Sociedad,N,NaN,...,0,1,0,0,0,0,0,0,NaN,NaN
3,2023-11-07 00:00:00,Tue,Champions Lg,Group stage,Away,L 0–1,es Barcelona,ua Shakhtar Donetsk,N,NaN,...,0,0,0,0,2,0,1,0,NaN,NaN
4,2023-11-12 00:00:00,Sun,La Liga,Matchweek 13,Home,W 2–1,Barcelona,Alavés,Y,DM,...,0,0,1,0,1,0,2,0,NaN,NaN

In [29]:
df_temp['Min'] = df_temp['Min'].astype(str).str.extract(r'(\d+)')

In [30]:
import pandas as pd

files = {
    "2019-20": "pedri2019.xlsx",
    "2020-21": "pedri2020.xlsx",
    "2021-22": "pedri2021.xlsx",
    "2022-23": "pedri2022.xlsx",
    "2023-24": "pedri2023.xlsx",
    "2024-25": "pedri2025(ongoing).xlsx"
}

dfs = []

for season, file in files.items():
    df_temp = pd.read_excel(f"/content/{file}", header=1)

    df_temp.columns = [str(col).strip() for col in df_temp.columns]
    df_temp = df_temp.loc[:, ~df_temp.columns.duplicated()]

    if 'Comp' in df_temp.columns:
        df_temp = df_temp[df_temp['Comp'] != 'Comp']

    for col in df_temp.columns:
        if 'Min' in str(col):
            df_temp['Min'] = df_temp[col]

    df_temp['Min'] = df_temp['Min'].astype(str).str.extract(r'(\d+)')
    df_temp['Min'] = pd.to_numeric(df_temp['Min'], errors='coerce')

    df_temp = df_temp[df_temp['Min'] <= 120]

    df_temp['Season'] = season

    dfs.append(df_temp)

df = pd.concat(dfs, ignore_index=True)

season_avg = df.groupby('Season')['Min'].mean()
print(season_avg)

KeyError: 'Min'

In [31]:
import pandas as pd

files = {
    "2019-20": "pedri2019.xlsx",
    "2020-21": "pedri2020.xlsx",
    "2021-22": "pedri2021.xlsx",
    "2022-23": "pedri2022.xlsx",
    "2023-24": "pedri2023.xlsx",
    "2024-25": "pedri2025(ongoing).xlsx"
}

dfs = []

for season, file in files.items():
    df_temp = pd.read_excel(f"/content/{file}", header=1)

    df_temp.columns = [str(col).strip() for col in df_temp.columns]
    df_temp = df_temp.loc[:, ~df_temp.columns.duplicated()]

    if 'Comp' in df_temp.columns:
        df_temp = df_temp[df_temp['Comp'] != 'Comp']

    min_col = None
    for col in df_temp.columns:
        if 'Min' in str(col):
            min_col = col
            break

    if min_col is None:
        print(f"Skipping {season} (no Min column found)")
        continue

    df_temp['Min'] = df_temp[min_col]
    df_temp['Min'] = df_temp['Min'].astype(str).str.extract(r'(\d+)')
    df_temp['Min'] = pd.to_numeric(df_temp['Min'], errors='coerce')

    df_temp = df_temp[df_temp['Min'] <= 120]

    df_temp['Season'] = season
    dfs.append(df_temp)

df = pd.concat(dfs, ignore_index=True)

season_avg = df.groupby('Season')['Min'].mean()
print(season_avg)

Skipping 2023-24 (no Min column found)
Season
2019-20    78.416667
2020-21    68.516667
2021-22    75.000000
2022-23    77.000000
2024-25    70.577778
Name: Min, dtype: float64

In [32]:
df_2023 = pd.read_excel("/content/pedri2023.xlsx", header=1)
print(df_2023.columns)

Index([2023-08-13 00:00:00,               'Sun',           'La Liga',
             'Matchweek 1',              'Away',             'D 0–0',
               'Barcelona',            'Getafe',                 'Y',
                      'AM',                  78,                   0,
                     '0.1',               '0.2',               '0.3',
                         1,               '0.4',               '0.5',
                     '0.6',               '0.7',               '1.1',
                     '0.8',               '0.9',               '1.2',
                    '0.10',              '0.11',       'Unnamed: 26',
             'Unnamed: 27'],
      dtype='object')

In [33]:
df_2023 = pd.read_excel("/content/pedri2023.xlsx", header=1)

df_2023.columns = [str(col).strip() for col in df_2023.columns]

df_2023 = df_2023[df_2023['Comp'] != 'Comp']

# 👇 CHANGE THIS INDEX BASED ON WHAT YOU SEE
df_2023['Min'] = df_2023.iloc[:, 10]

df_2023['Min'] = df_2023['Min'].astype(str).str.extract(r'(\d+)')
df_2023['Min'] = pd.to_numeric(df_2023['Min'], errors='coerce')

df_2023 = df_2023[df_2023['Min'] <= 120]

print(df_2023['Min'].mean())

KeyError: 'Comp'

In [34]:
df_2023 = pd.read_excel("/content/pedri2023.xlsx", header=None)

# check raw structure
print(df_2023.head())
print(df_2023.iloc[0])

                    0    1        2             3      4       5          6   \
0                 Date  Day     Comp         Round  Venue  Result      Squad
1  2023-08-13 00:00:00  Sun  La Liga   Matchweek 1   Away   D 0–0  Barcelona
2  2023-08-20 00:00:00  Sun  La Liga   Matchweek 2   Home   W 2–0  Barcelona
3                  NaN  NaN      NaN           NaN    NaN     NaN        NaN
4  2023-11-04 00:00:00  Sat  La Liga  Matchweek 12   Away   W 1–0  Barcelona

              7      8    9   ...    18   19   20   21   22    23   24   25  \
0       Opponent  Start  Pos  ...  CrdR  Fls  Fld  Off  Crs  TklW  Int   OG
1         Getafe      Y   AM  ...     0    0    1    0    0     1    0    0
2          Cádiz      Y   AM  ...     0    1    2    0    2     2    0    0
3            NaN    NaN  NaN  ...   NaN  NaN  NaN  NaN  NaN   NaN  NaN  NaN
4  Real Sociedad      N  NaN  ...     0    1    0    0    0     0    0    0

      26     27
0  PKwon  PKcon
1    NaN    NaN
2    NaN    NaN
3    NaN    NaN
4    NaN    NaN

[5 rows x 28 columns]
0         Date
1          Day
2         Comp
3        Round
4        Venue
5       Result
6        Squad
7     Opponent
8        Start
9          Pos
10         Min
11         Gls
12         Ast
13          PK
14       PKatt
15          Sh
16         SoT
17        CrdY
18        CrdR
19         Fls
20         Fld
21         Off
22         Crs
23        TklW
24         Int
25          OG
26       PKwon
27       PKcon
Name: 0, dtype: object

In [35]:
df_2023 = pd.read_excel("/content/pedri2023.xlsx", header=1)

df_2023.columns = [str(col).strip() for col in df_2023.columns]
df_2023 = df_2023.loc[:, ~df_2023.columns.duplicated()]

# print columns so we can identify Min manually
print(df_2023.columns)

Index(['2023-08-13 00:00:00', 'Sun', 'La Liga', 'Matchweek 1', 'Away', 'D 0–0',
       'Barcelona', 'Getafe', 'Y', 'AM', '78', '0', '0.1', '0.2', '0.3', '1',
       '0.4', '0.5', '0.6', '0.7', '1.1', '0.8', '0.9', '1.2', '0.10', '0.11',
       'Unnamed: 26', 'Unnamed: 27'],
      dtype='object')

In [36]:
print(df_2023.columns)

Index(['2023-08-13 00:00:00', 'Sun', 'La Liga', 'Matchweek 1', 'Away', 'D 0–0',
       'Barcelona', 'Getafe', 'Y', 'AM', '78', '0', '0.1', '0.2', '0.3', '1',
       '0.4', '0.5', '0.6', '0.7', '1.1', '0.8', '0.9', '1.2', '0.10', '0.11',
       'Unnamed: 26', 'Unnamed: 27'],
      dtype='object')

In [37]:
df_2023 = pd.read_excel("/content/pedri2023.xlsx", header=1)

df_2023.columns = [str(col).strip() for col in df_2023.columns]
df_2023 = df_2023.loc[:, ~df_2023.columns.duplicated()]

df_2023['Min'] = df_2023.iloc[:, 10]

df_2023['Min'] = df_2023['Min'].astype(str).str.extract(r'(\d+)')
df_2023['Min'] = pd.to_numeric(df_2023['Min'], errors='coerce')

df_2023 = df_2023[df_2023['Min'] <= 120]

df_2023['Season'] = "2023-24"

print(df_2023['Min'].mean())

57.743589743589745

In [38]:
played = df.groupby('Season').size()
print(played)

Season
2019-20    36
2020-21    60
2021-22    24
2022-23    41
2024-25    45
dtype: int64

In [40]:
dfs.append(df_2023)

In [41]:
df = pd.concat(dfs, ignore_index=True)

In [42]:
involvement = df.groupby('Season').size()
print(involvement)

Season
2019-20    36
2020-21    60
2021-22    24
2022-23    41
2023-24    39
2024-25    45
dtype: int64

In [43]:
involvement = df.groupby('Season').size()

involvement_norm = involvement / involvement.max()

print(involvement_norm)

Season
2019-20    0.600000
2020-21    1.000000
2021-22    0.400000
2022-23    0.683333
2023-24    0.650000
2024-25    0.750000
dtype: float64

In [44]:
avg_involvement = involvement_norm.mean()

fitness = involvement_norm.apply(
    lambda x: "High Involvement" if x > avg_involvement else "Low Involvement"
)

print(fitness)

Season
2019-20     Low Involvement
2020-21    High Involvement
2021-22     Low Involvement
2022-23    High Involvement
2023-24     Low Involvement
2024-25    High Involvement
dtype: object

In [45]:
df['Involvement_Type'] = df['Season'].map(fitness)

df.groupby('Involvement_Type')[['Gls','Ast','Sh','TklW','Int']].mean()

                      Gls       Ast        Sh      TklW       Int
Involvement_Type
High Involvement  0.10274  0.136986  0.734266  0.881119  0.678322
Low Involvement      0.15  0.116667  1.172414  0.965517  0.551724

In [46]:
import pandas as pd


involvement = df.groupby('Season').size()
involvement_norm = involvement / involvement.max()
avg_involvement = involvement_norm.mean()

fitness = involvement_norm.apply(
    lambda x: "High Involvement" if x > avg_involvement else "Low Involvement"
)

df['Involvement_Type'] = df['Season'].map(fitness)



team = "Osasuna"

team_high = df[
    (df['Opponent'] == team) &
    (df['Involvement_Type'] == "High Involvement")
]


if len(team_high) == 0:
    team_high = df[df['Involvement_Type'] == "High Involvement"]


pred = team_high[['Gls','Ast','Sh','TklW','Int']].mean()


prediction = pd.DataFrame(pred, columns=["Expected_per_match"]).T

prediction["Goal_Prob_%"] = prediction["Gls"] * 100
prediction["Assist_Prob_%"] = prediction["Ast"] * 100

prediction["Shots_range"] = prediction["Sh"].apply(lambda x: "0-1" if x < 1 else "1-2")
prediction["Def_Actions_range"] = (prediction["TklW"] + prediction["Int"]).apply(
    lambda x: "1-2" if x < 2 else "2-3"
)

print(prediction)

                    Gls  Ast   Sh TklW  Int Goal_Prob_% Assist_Prob_%  \
Expected_per_match  0.2  0.2  1.0  1.0  1.4        20.0          20.0

                   Shots_range Def_Actions_range
Expected_per_match         1-2               2-3